// deltarune-data.js: the fights, phases and attacks the Deltarune Trainer tracks.
// Plain data, no game files needed.

export const FIGHTS = [
  {"id":"jevil","name":"JEVIL","chapter":1,"phases":[{"id":2,"name":"80% HP"},{"id":3,"name":"60% HP"},{"id":4,"name":"40% HP"},{"id":5,"name":"FINAL CHAOS"}],"attacks":[{"id":0,"name":"CHAOS CLONES"},{"id":1,"name":"RING AROUND"},{"id":2,"name":"HEART BOMBS"},{"id":3,"name":"DEVILSKNIFE"},{"id":4,"name":"CAROUSEL"},{"id":5,"name":"CLUB BOMBS"},{"id":6,"name":"DIAMOND RISE"},{"id":7,"name":"SIDE RINGS"},{"id":8,"name":"CAROUSEL II"},{"id":9,"name":"SPADE BOMBS"},{"id":10,"name":"CLUB FLYERS"},{"id":11,"name":"DEVILSKNIFE II"},{"id":12,"name":"DIAMOND CLONES"},{"id":13,"name":"CHAOS BOMB"},{"id":14,"name":"DIAMOND STORM"},{"id":15,"name":"FINAL CHAOS"}]},
  {"id":"king","name":"KING","chapter":1,"phases":[],"attacks":[{"id":0,"name":"SPADE VOLLEY"},{"id":1,"name":"CHAIN KING"},{"id":2,"name":"SPADE RAIN"},{"id":3,"name":"BOUNCING BOX"},{"id":4,"name":"CHAIN KING II"},{"id":5,"name":"CHAIN SWING"},{"id":6,"name":"SPADE SPIRAL"},{"id":7,"name":"BOUNCING BOX II"},{"id":8,"name":"SPADE STORM"},{"id":9,"name":"CHAIN KING III"},{"id":10,"name":"CHAIN SWING II"}]},
  {"id":"spamton_neo","name":"SPAMTON NEO","chapter":2,"phases":[{"id":2,"name":"LATE FIGHT"},{"id":3,"name":"UNDER 30% HP"},{"id":4,"name":"FINALE"}],"attacks":[{"id":0,"name":"FLYING HEADS"},{"id":1,"name":"RECREW COLUMNS"},{"id":2,"name":"HEART ATTACK"},{"id":3,"name":"PHONE CALL"},{"id":4,"name":"PHONE HANDS"},{"id":5,"name":"FACE ATTACK"},{"id":6,"name":"HEART ATTACK II"},{"id":7,"name":"FLYING HEADS II"},{"id":8,"name":"PHONE HANDS II"},{"id":9,"name":"PHONE CALL II"},{"id":10,"name":"RECREW COLUMNS II"},{"id":11,"name":"HEART ATTACK III"},{"id":12,"name":"PHONE CALL III"},{"id":13,"name":"NEO FINALE"}]},
  {"id":"queen","name":"QUEEN","chapter":2,"phases":[{"id":2,"name":"75% HP"},{"id":3,"name":"50% HP"},{"id":4,"name":"25% HP"}],"attacks":[{"id":0,"name":"BERDLY TORNADO"},{"id":1,"name":"STOMP"},{"id":2,"name":"EXPLOSION"},{"id":3,"name":"QUEEN LASER"},{"id":4,"name":"SOCIAL MEDIA"},{"id":5,"name":"PLUG"},{"id":6,"name":"QUEEN LASER II"},{"id":7,"name":"SOCIAL MEDIA II"},{"id":8,"name":"BERDLY TORNADO II"},{"id":9,"name":"EXPLOSION II"},{"id":10,"name":"PLUG II"},{"id":11,"name":"QUEEN LASER III"},{"id":12,"name":"WINE"},{"id":13,"name":"WINE II"},{"id":14,"name":"WINE III"},{"id":15,"name":"QUEEN ULTIMATE"}]},
  {"id":"tenna","name":"TENNA","chapter":3,"phases":[{"id":2,"name":"HALF HP"},{"id":3,"name":"FINAL EPISODE"}],"attacks":[{"id":0,"name":"TENNA ATTACK 1"},{"id":1,"name":"TENNA ATTACK 2"},{"id":2,"name":"TENNA ATTACK 3"},{"id":3,"name":"RHYTHM GAME"},{"id":4,"name":"COOKING"},{"id":5,"name":"COWBOY"},{"id":6,"name":"COWBOY II"},{"id":7,"name":"BATTLE"},{"id":8,"name":"BATTLE II"},{"id":9,"name":"SUSIEZILLA"},{"id":10,"name":"SUSIEZILLA II"},{"id":11,"name":"SUSIEZILLA III"}]},
  {"id":"knight","name":"ROARING KNIGHT","chapter":3,"phases":[{"id":2,"name":"PHASE 2"},{"id":3,"name":"PHASE 3"},{"id":4,"name":"PHASE 4 (80%)"}],"attacks":[{"id":0,"name":"PHASE 1 ATTACK 1"},{"id":1,"name":"PHASE 1 ATTACK 2"},{"id":2,"name":"PHASE 1 ATTACK 3"},{"id":3,"name":"PHASE 1 ATTACK 4"},{"id":4,"name":"PHASE 1 ATTACK 5"},{"id":5,"name":"PHASE 2 ATTACK 1"},{"id":6,"name":"PHASE 2 ATTACK 2"},{"id":7,"name":"PHASE 2 ATTACK 3"},{"id":8,"name":"PHASE 2 ATTACK 4"},{"id":9,"name":"PHASE 2 ATTACK 5"},{"id":10,"name":"PHASE 3 ATTACK 1"},{"id":11,"name":"PHASE 3 ATTACK 2"},{"id":12,"name":"PHASE 3 ATTACK 3"},{"id":13,"name":"PHASE 3 ATTACK 4"},{"id":14,"name":"PHASE 3 ATTACK 5"},{"id":15,"name":"THE ROARING"}]},
  {"id":"gerson","name":"GERSON","chapter":4,"phases":[{"id":6,"name":"TURN 6"},{"id":12,"name":"TURN 12 (50%)"},{"id":16,"name":"TURN 16 (75%)"},{"id":20,"name":"FINAL HAMMER"}],"attacks":[{"id":0,"name":"TURN 1"},{"id":1,"name":"TURN 2"},{"id":2,"name":"TURN 3"},{"id":3,"name":"TURN 4"},{"id":4,"name":"TURN 5"},{"id":5,"name":"TURN 6"},{"id":6,"name":"TURN 7"},{"id":7,"name":"TURN 8"},{"id":8,"name":"TURN 9"},{"id":9,"name":"TURN 10"},{"id":10,"name":"TURN 11"},{"id":11,"name":"TURN 12"},{"id":12,"name":"TURN 13"},{"id":13,"name":"TURN 14"},{"id":14,"name":"TURN 15"},{"id":15,"name":"TURN 16"},{"id":16,"name":"TURN 17"},{"id":17,"name":"TURN 18"},{"id":18,"name":"TURN 19"},{"id":19,"name":"HAMMER OF JUSTICE"}]},
  {"id":"titan","name":"TITAN","chapter":4,"phases":[{"id":3,"name":"SHIELD RETURNS"},{"id":5,"name":"SHIELD RETURNS II"},{"id":6,"name":"THIRD UNLEASH"},{"id":7,"name":"REGENERATION"},{"id":8,"name":"OLD MAN"}],"attacks":[{"id":0,"name":"SWARM"},{"id":1,"name":"GAZE"},{"id":2,"name":"HEART GRIP"},{"id":3,"name":"UNLEASHED"},{"id":4,"name":"SLITHER"},{"id":5,"name":"SWARM II"},{"id":6,"name":"HANDS"},{"id":7,"name":"UNLEASHED II"},{"id":8,"name":"SLITHER II"},{"id":9,"name":"SWARM III"},{"id":10,"name":"HANDS II"},{"id":11,"name":"DESPERATION"},{"id":12,"name":"UNLEASHED III"}]},
  {"id":"pink","name":"PINK","chapter":5,"phases":[{"id":2,"name":"SECOND DATE"},{"id":3,"name":"GHOST"},{"id":4,"name":"FINALE"}],"attacks":[{"id":0,"name":"PURPLE CATS"},{"id":1,"name":"BOMB BACKSTORY"},{"id":2,"name":"CAT BEAT"},{"id":3,"name":"GEL PEN BOMBS"},{"id":4,"name":"FIRST CONCERT"},{"id":5,"name":"RANDOM CATS"},{"id":6,"name":"SPIN BOX"},{"id":7,"name":"3D TUNNEL"},{"id":8,"name":"NEW HAT BOMBS"},{"id":9,"name":"WISHLIST SONG"},{"id":10,"name":"QUICK SPIN"},{"id":11,"name":"ANIME FACE BOX"},{"id":12,"name":"BIG BOMB"},{"id":13,"name":"CAT CONGA"},{"id":14,"name":"TUNNEL RUSH"},{"id":15,"name":"FLIP CATS"},{"id":16,"name":"BOMB STORM"},{"id":17,"name":"ENCORE"}]},
  {"id":"flowery","name":"FLOWERY","chapter":5,"phases":[{"id":2,"name":"PHASE 2"},{"id":3,"name":"PHASE 3"},{"id":4,"name":"PHASE 4"},{"id":5,"name":"PHASE 5"},{"id":6,"name":"PHASE 6"}],"attacks":[{"id":0,"name":"WALL TUTORIAL"},{"id":1,"name":"PETAL JARONA"},{"id":2,"name":"HEDGE CHASE"},{"id":3,"name":"JARONA BARRAGE"},{"id":4,"name":"SETH'S BOXES"},{"id":5,"name":"AQUA KNIVES"},{"id":6,"name":"SETH'S BOXES EX"},{"id":7,"name":"ORANGE COMBO"},{"id":8,"name":"JUST KIDDING"},{"id":9,"name":"WILD CHASE"},{"id":10,"name":"JUSTICE CHASE"},{"id":11,"name":"SUPER JARONA"},{"id":12,"name":"HARD JARONA"}]},
];
